version: '3.9'

services:
  database:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=golang
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=568219
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10


  webapi:
    image: webapi
    build: ../
    ports:
      - "80:80"
    depends_on:
      database:
        condition: service_healthy
    command: ./school-marks-app